#!/usr/bin/env python3
"""
Generate the Sony OUI table for device discovery
================================================
Device discovery keeps a Bluetooth device when its name or its address prefix
(OUI) identifies Sony. This script reads the Wireshark `manuf` file, which
copies the IEEE MA-L registry, and writes the Sony prefixes to
`libs/sony-transport/src/SonyOuiTable.h`.

The IEEE server rejects scripted downloads, so the script uses the Wireshark
copy. Use --input to read a file that you downloaded yourself.

The table includes only the Sony companies that make audio and consumer
electronics. It excludes Sony Interactive Entertainment, because PlayStation
controllers use its prefixes.
"""

import argparse
import gzip
import sys
import urllib.request
from pathlib import Path

MANUF_URL = "https://www.wireshark.org/download/automated/data/manuf.gz"
OUTPUT = Path(__file__).resolve().parent / "libs/sony-transport/src/SonyOuiTable.h"

# Full vendor names as the registry writes them.
SONY_VENDORS = {
    "Sony Corporation",
    "Sony Home Entertainment&Sound Products Inc",
    "SONY Visual Products Inc.",
    "Sony Video & Sound Products Inc.",
}


def read_manuf(path: str | None) -> str:
    if path:
        data = Path(path).read_bytes()
    else:
        request = urllib.request.Request(MANUF_URL, headers={"User-Agent": "update_sony_ouis.py"})
        with urllib.request.urlopen(request, timeout=60) as response:
            data = response.read()
    if data[:2] == b"\x1f\x8b":
        data = gzip.decompress(data)
    return data.decode("utf-8")


def sony_ouis(manuf: str) -> list[tuple[int, str]]:
    result = {}
    for line in manuf.splitlines():
        if not line or line.startswith("#"):
            continue
        columns = line.split("\t")
        if len(columns) < 3:
            continue
        prefix = columns[0].strip()
        vendor = columns[2].strip()
        # Only 24-bit MA-L blocks. The smaller MA-M and MA-S blocks have a "/" length.
        if vendor not in SONY_VENDORS or "/" in prefix:
            continue
        result[int(prefix.replace(":", ""), 16)] = vendor
    return sorted(result.items())


def render(ouis: list[tuple[int, str]]) -> str:
    lines = [
        "// Generated by update_sony_ouis.py from the Wireshark manuf file. Do not edit.",
        f"// Source: {MANUF_URL}",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace sony::transport::detail {",
        "",
        "// Sorted. Each value is the first three octets of a Bluetooth address.",
        f"inline constexpr std::array<std::uint32_t, {len(ouis)}> kSonyOuis = {{",
    ]
    lines += [f"    0x{oui:06X}, // {vendor}" for oui, vendor in ouis]
    lines += ["};", "", "} // namespace sony::transport::detail", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input", help="read this manuf or manuf.gz file, not the download")
    parser.add_argument("--output", default=str(OUTPUT), help=f"output header (default: {OUTPUT})")
    args = parser.parse_args()

    ouis = sony_ouis(read_manuf(args.input))
    if not ouis:
        print("error: no Sony prefixes found. Did the manuf format change?", file=sys.stderr)
        return 1
    Path(args.output).write_text(render(ouis), encoding="utf-8")
    print(f"Wrote {len(ouis)} Sony prefixes to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
